### ISSUE TITLE
[Enhancement] more widget parameter

### ISSUE THREAD

**Issue by DJay-X** [lwitzani/homebridgeStatusWidget#10]
@lwitzani First of all thanks for this awesome script and your great work sharing with us all.

Is there a chance to have more widget parameter in the near future not only `user,,password,,ip` ?

I have four homebridge running and now using the widget four times.
Always changing systemGuiName = 'Raspberry Pi' to 
'HB Pi 3'
'HB Pi 3 2nd'
'HB macOS'
'HB NAS DS920+'

Also I always change bgColorMode = 'PURPLE' to 'BLUE_TO_RED'

It would be very helpful to have this parameters also permanent set.

example: "admin,,mypassword123,,http://192.168.178.33:8581,,HB Pi 3,,BLUE_TO_RED"

Thanks in advance for the consideration.

**Comment by lwitzani** [comment]
Hi,
I know this and i also thought about having more parameter there. At first I decided against it because it is tricky to set it up in the small widget window with lots of parameters. But guess i can add more parameter for the power users 👍🏻. I‘ll put it in my todo list... Keep an eye on the repo changelog to see when it‘s there (maybe in couple of days)

**Comment by DJay-X** [comment]
Thanks a lot. I think this will work now with the lates update [#19.11.2020 22:26](https://github.com/lwitzani/homebridgeStatusWidget/blob/main/CHANGELOG.md)
👍

**Comment by lwitzani** [comment]
Don‘t be so quick ;) i will push an Update in the next 1-2hours. After that everything can be modified. (Your config will be deleted because i needed to change it, so wait with co figuration for 2 more hours :D )

**Comment by lwitzani** [comment]
i pushed it. hope everything still works :D
