### ISSUE TITLE
White Widget since iOS18

### ISSUE THREAD

**Issue by R-Rennert** [lwitzani/homebridgeStatusWidget#63]
Hi,

since iOS18 and iPadOS18, the widget are only clean white, no text to see. In Sciptable the widget works Fine.
![image](https://github.com/user-attachments/assets/d9223b05-8bec-4d0a-bf1d-9d787aa6cfcf)

**Comment by lwitzani** [comment]
Hey :) thanks for letting me know. I have currently no iOS18 device next to me so i can’t check what’s going on. But anyway i guess it is not a problem in the script (since it works inside the app as you said) so i guess it will be fixed with some future Scriptable update. There was a similar case in the past that also got resolved that way. But if i know what the problem is i will fix it 👍🏻

**Comment by lwitzani** [comment]
![image](https://github.com/user-attachments/assets/1f6dea73-b1d5-4819-858b-bf10e8d830ac)


There is an update available. Can you give me feedback if it is fixed? Thanks

**Comment by R-Rennert** [comment]
Hi,With update works fine for me😊Thanks for your help.Am 29.09.2024 um 14:32 schrieb lwitzani ***@***.***>:﻿
image.jpeg (view on web)
There is an update available. Can you give me feedback if it is fixed? Thanks
